version: 2
jobs:
  test:
    working_directory: /go/src/github.com/kitsuyui/myip
    docker:
      - image: golang:1.14.2-stretch@sha256:8447ffeda05bf41f6cc0e1e5f5fdf4346c8173ca4b3fb9839f50625d3953fd73
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            ./bin/test.sh
            ./bin/coverage.sh
            bash <(curl -s https://codecov.io/bash)

  release:
    working_directory: /go/src/github.com/kitsuyui/myip
    docker:
      - image: golang:1.14.2-stretch@sha256:8447ffeda05bf41f6cc0e1e5f5fdf4346c8173ca4b3fb9839f50625d3953fd73
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            go get github.com/mitchellh/gox
            go get github.com/tcnksm/ghr
            BUILD_VERSION="$CIRCLE_TAG" ./bin/build.sh
            mkdir /tmp/releases
            mv ./build/myip_* /tmp/releases
            ghr -u "$CIRCLE_PROJECT_USERNAME" "$CIRCLE_TAG" /tmp/releases

workflows:
  version: 2
  build_and_release:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+.\d+$/
